# starting point는 application.yml

spring:
  profiles:
    active: prod # 현재 어떤 환경을 사용할지

# 추후 jar 실행 시
#java -jar <jar파일명>
#java "-Dspring.profiles.active=prod" -jar <jar파일명>
# 위와 같이 실행시 application.yml에 설정을 덮어 쓰기