#spring.application.name=board

server:
  port: 8081

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/basic
    username: root
    password: 1234
  jpa: # jpa ????
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect # innoDB ?? ??
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show_sql: true